version: '3.7'

services:
  facesapi:
    build: facesapi
    ports:
      - 81:8081
    volumes:
      - ./facesapi:/facesapi
    command: sh -c "sleep 10; gunicorn --workers=4 --bind=0.0.0.0:8081 api:app"
    depends_on:
      - postgresql

  facescruncher:
    build: facecruncher
    environment:
      - CELEBRITY_DATA_URL_LOCAL=http://celebritydata:8081
      - CELEBRITY_DATA_URL_REMOTE=http://localhost:8081
    depends_on:
      - rabbitmq
    command: sh -c "sleep 15s && python /facecruncher/src/watcher.py"

  rabbitmq:
    hostname: "rabbitmq"
    image: 'bitnami/rabbitmq:3.8'
    volumes:
      - rabbitmq_data:/bitnami
      - ./rabbitmq-isolated.conf:/opt/bitnami/rabbitmq/etc/rabbitmq/rabbitmq.config

  postgresql:
     image: 'bitnami/postgresql:12.1.0-r54'
     ports:
      - '5432:5432'
     volumes:
      - 'postgresql_data:/bitnami/postgresql'
     environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
  
  celebritydata:
    build: celebritydata
    ports:
      - 8081:8081

volumes:
  faces-data:
  rabbitmq_data:
  postgresql_data:
